<h1><?php echo $this->s_title; ?></h1>

<div><a href="<?php echo $this->url('mva-crud/new', array('module' => $this->s_module))?>">Add</a></div>

<?php if (count($this->as_messages)) { ?>
<div style="border: 2px solid blue">
<?php foreach ($this->as_messages as $s_msg) { ?>
<p><?php echo $s_msg?></p>
<?php } ?>
</div>
<?php } ?>

<div>
    <table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->aI_entities as $I_entity): ?>
        <tr class="odd gradeX">
            <td><?php echo $I_entity->getName()?></td>
            <td>
                <a href="<?php echo $this->url('mva-crud/edit', array('module' => $this->s_module, 'id' => $I_entity->getId()))?>">edit</a>
                -
                <a href="<?php echo $this->url('mva-crud/delete', array('module' => $this->s_module, 'id' => $I_entity->getId()))?>">delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
</div>